// Generated by CoffeeScript 1.7.1
(function() {
  var Extension, addHook, applySafely, createEditor, estraverse, expanders, getHookArgs, globalExtensions, globalHooks, hooksDo, onChange, parse, parser, registerExtension, widgetExpander, _;

  parser = require('./metadata');

  _ = require('underscore');

  estraverse = require('estraverse');

  expanders = require('expanders');

  globalHooks = {};

  globalExtensions = {};

  widgetExpander = expanders.createExpander('displayWidget');

  Extension = (function() {
    function Extension(id) {
      if (id in globalExtensions) {
        throw new Error("An extension named '" + id + "' is already registered");
      }
      this._id = id || _.uniqueId('ext-');
      globalExtensions[this._id] = this;
      this._hooks = {};
      this._expander = expanders.createExpander('extras');
      this.on = _.partial(addHook, this._id, globalHooks);
    }

    Extension.prototype.addWidget = function(pos, node, type) {
      if (widgetExpander.has(node, 'displayWidget')) {
        throw new Error('Conflicting widgets on node');
      }
      widgetExpander.set(node, 'displayWidget', {
        type: type,
        pos: pos
      });
    };

    Extension.prototype.getWidget = function(node) {
      return widgetExpander.get(node, 'displayWidget');
    };

    Extension.prototype.setExtras = function(node, data) {
      return this._expander.set(node, 'extras', data);
    };

    Extension.prototype.getExtras = function(node, ext) {
      var exp;
      exp = (ext != null ? ext._expander : void 0) || this._expander;
      return exp.get(node, 'extras');
    };

    Extension.prototype.BEFORE = 'before';

    Extension.prototype.AFTER = 'after';

    Extension.prototype.REPLACE = 'replace';

    return Extension;

  })();

  addHook = function(id, hookState, hookName, func) {
    var hooks;
    if (id == null) {
      id = _.uniqueId('hook-');
    }
    hooks = hookState[hookName] != null ? hookState[hookName] : hookState[hookName] = {};
    if (hooks[id] == null) {
      hooks[id] = [];
    }
    hooks[id].push(func);
  };

  hooksDo = function(hook, iter) {
    return _.each(hook, function(hookFns, id) {
      return _.each(hookFns, function(fn) {
        return iter(fn, id);
      });
    });
  };

  registerExtension = function(id, initFn) {
    var ext;
    ext = new Extension(id, initFn);
    if (initFn != null) {
      initFn.call(null, ext);
    }
    return ext;
  };

  parse = function(hooks, source) {
    var hookArgs, tree;
    tree = parser.parse(source);
    hookArgs = getHookArgs(tree);
    hooksDo(globalHooks['parse'], function(func, id) {
      return applySafely(func, hookArgs);
    });
    return tree;
  };

  createEditor = function(el) {
    var editor;
    editor = CodeMirror.fromTextArea(el);
    editor.on('change', _.debounce(onChange, 250));
    editor.setValue(editor.getValue() + ' ');
    return editor;
  };

  getHookArgs = function(ast) {
    var nodes;
    nodes = [];
    estraverse.traverse(ast, {
      enter: function(node) {
        return nodes.push(node);
      }
    });
    return [_.chain(nodes), _.chain(ast.comments)];
  };

  applySafely = function(func, args) {
    var e;
    try {
      return func.apply(null, args);
    } catch (_error) {
      e = _error;
      return console.log(e.stack || e);
    }
  };

  onChange = function(cm, changeObj) {
    var e, hookArgs, tree;
    try {
      tree = parse(globalHooks, cm.getValue());
    } catch (_error) {
      e = _error;
      console.log(e);
      return;
    }
    hookArgs = getHookArgs(tree);
    hooksDo(globalHooks['display'], function(func, id) {
      return applySafely(func, hookArgs);
    });
    return hooksDo(globalHooks['render'], function(func, id) {
      return applySafely(func, hookArgs);
    });
  };

  module.exports = {
    createEditor: createEditor,
    extensionsTempHack: globalExtensions,
    on: _.partial(addHook, null, globalHooks),
    onChange: onChange,
    parse: parse,
    registerExtension: registerExtension,
    traverse: estraverse.traverse
  };

}).call(this);
